INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE,TITLE) VALUES(1, 'TEST AUTHOR1', 'TEST ISBN', '2002-02-02', 'TEST KITAP 1');
INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE,TITLE) VALUES(2, 'TEST AUTHOR2', 'TEST ISBN2', '2002-02-02', 'TEST KITAP 2');
INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE,TITLE) VALUES(3, 'TEST AUTHOR3', 'TEST ISBN3', '2002-02-02', 'TEST KITAP 3');